---
- name: update pacman cache
  pacman: update_cache=yes
  become: yes

- name: install reflector
  pacman: name=reflector state=present
  become: yes

- name: check if mirror list was recently updated
  stat: path="/etc/pacman.d/mirrorlist"
  register: mirrorlist_age

- name: update pacman mirrorlist
  command: /usr/bin/reflector --country "United States" -l 200 -p http --sort rate --save /etc/pacman.d/mirrorlist
  become: yes
  when: "{{ mirrorlist_age.stat.mtime }} < {{ ansible_date_time.epoch|int - (60 * 60 * 24) }}"

- name: update pacman package lists
  command: /usr/bin/pacman -Syy --noconfirm
  become: yes

- name: perform full upgrade
  command: /usr/bin/pacman -Su --noconfirm
  become: yes
